language: python
python: 3.7
install: pip install -e .
script: pytest
deploy:
  provider: pypi
  username: __token__
  password:
    secure: GPaLuFOgm85PSR5bBiBYL0xzWFzY6kHZsqgt+tizgwzhqm5ipdA0FEByuwMwWcXLbiUylaXw9TdoyWDz6x2yypaGwgl/rdYAIfyRWdJkg4tr8RhUZnhbjJgOJQI56yUeJskafhpzQ9efek8QBEw7Elo+Zd2sMrmojlqeX0yKWGOcPk1U00KXY3J1pDMGQ9LJ4B8QE30WVMQiJsPyt3K+NaQSDBfmjzor4hC/+z9sq/KX7BKFEltAs6/EkGbneoU0lXK1kDLEaqY6B2zIO+BXYp/OG1eU4o0Ys8FCF2+HqoeZ6RTiKirId95y96WbQakuW2JI4aoByYZKmJaegcuqR/yKm3/Cb77So5gvHiMdAtDPHMn0jV5f9/vfRLECzvpQ8VPH5QSOl8pOPyqoj9Dshfi42ZQFs1Xm8GddKwAxWbzsMH70PUklTLrKEiiuU4X6iAHXkGdZDoh++3dMsBlJ/gvpin74sxyMESPkwY9pqzomtQASg2ablOhMy0jmyfs9W0RPDrgdswD+nr2oBBhZKi5Qt/LACXVJ3oahZKqvF2PuEJR4cT5v1wpMLLhLOlmJqfWLlaBAjVA1NVVcHiegxS+lZRZXEUHmrFB7StoCvjzjCtWBYdUQgaHpo626VO20aOw503uoPsBTqqzvIon6ijRiJYYV9NJwSgJijbJZvgo=
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch: master
