language: python
python: 3.6
install: pip install -e .
script: pytest
deploy:
  provider: pypi
  username: __token__
  password:
    secure: ZDGPKQQ2St95cTonal3Anz6p3ZIRvXtymHt8GXPjogaOFSH6JyMG18QdAiviHBkw7UbGnvURNBsiKtriTPqcDRkWGXjpASdVYcLeYLNCSKwNH1nEnn0wQuEgBKPwHhn50R4U6KGLvQA7rhuz/UyUkZtXZhpQ3vHqS0Iu+ISU9EjCqjD8jczIlS6d9euqnHkRm8Xp7O7dXLxJ93M8AVaUIqEF5mpEbNk4LltDyfRautKCGIcFuXgc3YgNp7JuQxAHJE17Q09C2Y4KbEjkBpx83y1jJ+BsvGX6tAqAp9cwv8+vF+dc/xro/rWqG3Sw3ifl+9s0Bn4XrLK8S4S/aNtHOILOD36nY1n/2f6vqum6/7RDBx74WGYHAgj3oRpPARdQSaKHh9o1bvnDdOlc/qo8Ntf546NbbhvB+1VOGQrqcL+6hghMFZpXzwxHEj1y9mtuWAtTU6KevWQOISpM0vQ9kR9TXhZCwaKFvWoVN4EBzPw0cjy1R7mtPToYvMnZOprmTIbwbGm5fW7qiqiFMmJwtbUfaaLSa3Xl9MetHjlT5sXo2QWN/S7Zi0WdoQXjy+ZMsl/U/pig+PsWdITWzNnT+b5TuOQPAFBKohTN6Hx7QmpOiVXMJGraVxY1FZYDajJRE4LYmr0lHsIdNIpEx3B7ataQJQVGZfMimZi+NWExl6w=
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch: master
